from dataclasses import dataclass

import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler


FEATURES = [
    "rainfall_mm",
    "soil_moisture",
    "pore_pressure_kpa",
    "slope_movement_mm_day",
    "gnss_displacement_mm",
    "inclinometer_deg",
    "groundwater_head_m",
]
DEFAULT_SEQUENCE_LENGTH = 7


@dataclass
class PredictionResult:
    mode: str
    predicted_fos: float | None
    message: str
    mae: float | None = None
    rmse: float | None = None
    training_loss: float | None = None
    validation_loss: float | None = None


def make_sequences(frame: pd.DataFrame, sequence_length: int = DEFAULT_SEQUENCE_LENGTH):
    required = FEATURES + ["fos"]
    missing = [column for column in required if column not in frame.columns]
    if missing:
        raise ValueError(f"Required prediction column is missing: {missing[0]}")
    clean = frame[required].apply(pd.to_numeric, errors="coerce").dropna().reset_index(drop=True)
    feature_values = clean[FEATURES].to_numpy(dtype=np.float32)
    target_values = clean["fos"].to_numpy(dtype=np.float32)
    sequences, targets = [], []
    for end in range(sequence_length, len(clean)):
        sequences.append(feature_values[end - sequence_length:end])
        targets.append(target_values[end])
    return np.asarray(sequences, dtype=np.float32), np.asarray(targets, dtype=np.float32)


def predict_stability(frame: pd.DataFrame, sequence_length: int = DEFAULT_SEQUENCE_LENGTH) -> PredictionResult:
    sequences, targets = make_sequences(frame, sequence_length)
    if len(sequences) < 20:
        latest = float(frame["fos"].dropna().iloc[-1]) if "fos" in frame and frame["fos"].notna().any() else 2.91
        return PredictionResult(
            mode="DEMO",
            predicted_fos=round(max(0.6, latest - 0.23), 2),
            message="Demonstration estimate — not generated from a trained LSTM model.",
        )

    try:
        import tensorflow as tf
    except ImportError:
        latest = float(targets[-1])
        return PredictionResult(
            mode="DEMO",
            predicted_fos=round(max(0.6, latest - 0.23), 2),
            message="TensorFlow is not installed. Showing a deterministic demonstration estimate.",
        )

    split = max(1, int(len(sequences) * 0.8))
    feature_scaler = StandardScaler()
    x_train = sequences[:split].reshape(-1, len(FEATURES))
    feature_scaler.fit(x_train)
    scaled = feature_scaler.transform(sequences.reshape(-1, len(FEATURES))).reshape(sequences.shape)
    x_train, x_validation = scaled[:split], scaled[split:]
    y_train, y_validation = targets[:split], targets[split:]
    if not len(x_validation):
        return PredictionResult("DEMO", round(float(targets[-1]), 2), "More validation observations are needed.")

    tf.keras.utils.set_random_seed(17)
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(sequence_length, len(FEATURES))),
        tf.keras.layers.LSTM(32, return_sequences=True),
        tf.keras.layers.Dropout(0.15),
        tf.keras.layers.LSTM(16),
        tf.keras.layers.Dense(1),
    ])
    model.compile(optimizer="adam", loss="mean_squared_error")
    history = model.fit(x_train, y_train, validation_data=(x_validation, y_validation), epochs=50, batch_size=16, verbose=0, callbacks=[tf.keras.callbacks.EarlyStopping(patience=6, restore_best_weights=True)])
    validation_predictions = model.predict(x_validation, verbose=0).reshape(-1)
    future = model.predict(scaled[-1:].copy(), verbose=0).reshape(-1)[0]
    return PredictionResult(
        mode="TRAINED_LSTM",
        predicted_fos=round(float(future), 3),
        message="Estimate generated by an LSTM trained on the available time-series observations.",
        mae=round(float(mean_absolute_error(y_validation, validation_predictions)), 4),
        rmse=round(float(np.sqrt(mean_squared_error(y_validation, validation_predictions))), 4),
        training_loss=round(float(history.history["loss"][-1]), 5),
        validation_loss=round(float(history.history["val_loss"][-1]), 5),
    )